import { MenuItem, User, FeedbackEntry } from './types';

export const MOCK_USER: User = {
  id: 'atharva-001',
  name: 'Atharva',
  role: 'student',
  messType: 'VEG',
  avatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAfqbMWms-IS8xg5Joij6ssAbBQB5zpQ-aDS9egfApxmoCiMjMrblLdnwyxO0OquPVpSwpDSRT9vmXVSN-z2xR63R-EHdTXmItgI3j6V7DnEN55ZlsmLHJHzSWlwqUPSIhMwvX9uFBZMZIrJ9mIBvBNPnPVe_4FQIBZTCyY3P_UkH_uUrCDyFGxchRB2QuUsSl7f9m9Da0FvxKMTumIzxfgz00sTucf69kVND2GLUs76iqKCvNyzp77EJFtLxkVCh1Z8Wpwp6iAFP7h',
};

export const MOCK_ADMIN: User = {
  id: 'admin-001',
  name: 'Admin User',
  role: 'admin',
  messType: 'NON-VEG',
  avatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBVvKrQ6iZwAUeaIQLPig_dDg0IINGscs7bVMpiF_VzuYPwN2MJdLzCQ2OcjpGaxAfiXfneD9nYyztHAaaBGazq30V1NI1_fNbMi6320ilaVHxRUYDpA9fqXa_XIHT5Tb5-dC_E0uMWS_PMiYOjPJKSdk5BB5kSMWqi_mUnTLA7oXu_oDqk4j9YU1Q2FJoUSzJezYvUidFDx1sTiedIkv2QYnqM-HYAe00c1ilx0-VWrTWPVU7cHc6FCEB7GgGye9GLoLUASJRjzoNR',
};

export const MENU_ITEMS: MenuItem[] = [
  {
    id: '1',
    name: 'Artisan Avocado Toast',
    description: 'Toasted sourdough topped with smashed organic avocados, heirloom cherry tomatoes, and a sprinkle of pumpkin seeds.',
    calories: 420,
    protein: 12,
    carbs: 38,
    fats: 24,
    type: 'VEG',
    category: 'Breakfast',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDsB3O-EF_7tO_-_hOun-2rR0fTgynRhIP_En5pDOJH7oYv8UPO9G_hUh2fsedqfIryc-lKygNOSqi8ol7IefyNlXdTkAGixgf_qsE_DIFsT239idmgx9QM4bgzNUU2uDZ1a4LMqaBJNmy50t2pE9Mb4uuKgAfkwdaHu1QLtPMBilheu5UOzZnJmWa_AR2Shgj8Bz_tHJKNSYnTW2jH_qt2CD_qMRH8wC0HSBFzgIXfk2aZYZ7Za0rEaVFeqf57x8QY118i_Z6dvQ9L',
    tags: ['Fiber', 'Healthy Fats'],
  },
  {
    id: '2',
    name: 'Greek Berry Parfait',
    description: 'Thick probiotic yogurt layered with wildflower honey, toasted oats, and seasonal woodland berries.',
    calories: 310,
    protein: 18,
    carbs: 42,
    fats: 6,
    type: 'VEG',
    category: 'Breakfast',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBk4w67p8A4F_hYNkb4GZxIEevjVBCxWrpmDD9igxoM6LmQwdAWi8yMQaWHhPiAybCb0Je7H0QdeNSco-L8jjhfkt6jkFWB115Y7WbqSv5I1nuQqrvg_ABEBhTGVClSUF7NmUhrqawgPUb5k88fBfqWn9vTJDfgQx8CBFxGeix4WUAqGcO8rngR850qdQU0r5bY7aoCFaoe5mBRALEgaXr9nN5xQ4oM8Puh0eUTxp_d-Zpa-Vfhmwz9BL1pqj42T38lx-_118yHvOm2',
    tags: ['Antioxidant'],
  },
  {
    id: '3',
    name: 'Nordic Salmon Bowl',
    description: 'Miso-glazed Atlantic salmon served over a bed of fluffy quinoa, charred broccoli, and sesame-dressed edamame.',
    calories: 580,
    protein: 34,
    carbs: 45,
    fats: 22,
    type: 'NON-VEG',
    category: 'Lunch',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAehZHJOC7_Bl1YyFkWT02DlEhVuL5t0UZHWctCxAx104vgdAuWv96x_7S3YDLjJRxtgp3_ak8rQ7OcqINGwxJzo6cFXIZLs043nT4R7A7HcGHx8kpYfZnnLBuIMRrHMUP280e7Kra4S4YRWr5ehTwR_SPZ5dqYBk58v5sNaU4H1zGUK0JWAXXmI7YYQqmmmN9PsGBHE8npmMXySK9E2yp6Cj8TqdpFXLfiYtK-jFPtGPtvz47zxCFmGG1MJusbIl4DaaPrR1DWxMmf',
    tags: ['Lean Protein'],
  },
  {
    id: '4',
    name: 'Garden Basil Pesto',
    description: 'Whole-grain penne tossed in a house-made basil and pine nut pesto, finished with aged parmesan and sun-dried tomatoes.',
    calories: 520,
    protein: 15,
    carbs: 64,
    fats: 28,
    type: 'VEG',
    category: 'Dinner',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAjNdnPVkXdSoACdfS7MBCyq3op57Yi_UmKR3LRePkAzL4X6VW0DjdOK610RgXTJELZLCZwJwAvEArK-ngYfsDWGl5uP8EsvxTrin_Reg4txpS5s9rl-hRgNfgVAYFKM8OIJj9xeQhl8MhXIOyxff-EPYQqZoJrkS6He4RXd4qNm8Wq7uVg_VNsQnnlKl_8yPYSlFESob1HhaczkEczQ7aHDVGR1Fp_-DEGXxYnmVVEgF4-tT1XCTANvH-jIcpQfWzYCD5VZ7mOebiM',
    tags: ['Whole Grain'],
  },
  {
    id: '5',
    name: 'Quinoa & Roasted Chickpea Bowl',
    description: 'Fresh meals curated for your metabolic profile.',
    calories: 420,
    protein: 18,
    carbs: 52,
    fats: 12,
    type: 'VEG',
    category: 'Lunch',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuD0N98TGpOXMYJZkQl3W4q4WoaVNz8dqv8L09hFgkwTfyHMiuRUBF5e6Un6bCCYVu-KKsO6-q6HXgXjf2BSgQZytmP5vzRhgXG-5jF1Re6Hu0U-45oQppBcAY4lbSdYDRxOKSq1rCWb-8wCugLQ1FJmx9ccqR5VMGiUk9EKM-86iTk1KFWvvBj2rEt6Sy8LwWbNbLaXYpiQ0y2o-9amU1hJBFw3ZZZd3ztz69xctjtCTGlOJsk9Hgjev6TRvZKTm6pcGrarPPQOK2eR',
    tags: ['18g Protein', '52g Carbs', '12g Fiber'],
  },
  {
    id: '6',
    name: 'Garden Harvest Tabbouleh',
    description: 'Fresh meals curated for your metabolic profile.',
    calories: 310,
    protein: 8,
    carbs: 35,
    fats: 5,
    type: 'VEG',
    category: 'Lunch',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAMbz6PCafvO2_OG7ZsOZ2hO5oDSSaqrjM-e8vJ2QMXhnooLQSDnxTjT2zYH8a54itpizHdiupcq0SbbKBy5J6NlhY7wD5zHoqIsuEPtm4zWNHMyC_L2-5KbiinPnSJiZj01vvbHYoLhKXMuPx0bn8p47n32SmeeyfwNxHHkt-4Jk3zXlWTvigot4-IGquB6uxVIDucVek6MkvSvrcQAsABzuzGeMiHanROVa7Txeiw8zFPSb8TAlqNRtunQmPLXG0NpIugPqICTemh',
    tags: ['8g Protein', '35g Carbs', 'Low Fat'],
  },
];

export const FEEDBACK_ENTRIES: FeedbackEntry[] = [
  {
    id: 'f1',
    date: 'Oct 24, 12:30',
    dish: 'Butter Chicken',
    sentiment: 'POS',
    comment: 'Best meal of the week so far, loved the spice balance.',
    block: 'Block A',
  },
  {
    id: 'f2',
    date: 'Oct 24, 13:15',
    dish: 'Steamed Tapioca',
    sentiment: 'NEG',
    comment: 'A bit too dry today. Needed more curry accompaniment.',
    block: 'Block C',
  },
  {
    id: 'f3',
    date: 'Oct 23, 19:45',
    dish: 'Paneer Tikka',
    sentiment: 'POS',
    comment: 'Perfectly grilled. Thank you for the extra lime!',
    block: 'Block B',
  },
];
